### ISSUE TITLE
Conact Magento JS Files

### ISSUE THREAD

**Issue by mklooss** [webcomm/magento-boilerplate#100]
we discussed internal (with @riker09) about to merge the origin magento files also to the scripts.js in gulp/grunt

*Magento Head Example*
```
<script type="text/javascript" src="http://localhost/js/prototype/prototype.js?v1"></script>
<script type="text/javascript" src="http://localhost/js/lib/ccard.js?v1"></script>
<script type="text/javascript" src="http://localhost/js/prototype/validation.js?v1"></script>
<script type="text/javascript" src="http://localhost/js/scriptaculous/builder.js?v1"></script>
<script type="text/javascript" src="http://localhost/js/scriptaculous/effects.js?v1"></script>
<script type="text/javascript" src="http://localhost/js/scriptaculous/dragdrop.js?v1"></script>
<script type="text/javascript" src="http://localhost/js/scriptaculous/controls.js?v1"></script>
<script type="text/javascript" src="http://localhost/js/scriptaculous/slider.js?v1"></script>
<script type="text/javascript" src="http://localhost/js/varien/js.js?v1"></script>
<script type="text/javascript" src="http://localhost/js/varien/form.js?v1"></script>
<script type="text/javascript" src="http://localhost/js/mage/translate.js?v1"></script>
<script type="text/javascript" src="http://localhost/js/mage/cookies.js?v1"></script>
```

concat all Magento files into one file (without uglify) - magento.js
conact all boilerplate files into one file (with uglify) - boilerplate.js
merge magento.js and boilerplate.js into scripts.js

so we only got 1 js file :D

**Comment by sensejus** [comment]
Just Add to your gruntfile.js something like this :)

var theme_path = 'skin/frontend/your_theme/default';
    var js_path = 'js';

 grunt.initConfig({
        concat: {
            dist: {
                files:[
                    {
                        src: [
                            js_path + '/prototype/prototype.js',
                            js_path + '/lib/jquery/jquery-1.10.2.min.js',
                            js_path + '/lib/jquery/noconflict.js',
                            js_path + '/lib/ccard.js',
                            js_path + '/prototype/validation.js',
                            js_path + '/scriptaculous/builder.js',
                            js_path + '/scriptaculous/effects.js',
                            js_path + '/scriptaculous/dragdrop.js',
                            js_path + '/scriptaculous/controls.js',
                            js_path + '/scriptaculous/slider.js',
                            js_path + '/varien/js.js',
                            js_path + '/varien/form.js',
                            js_path + '/mage/translate.js',
                            js_path + '/mage/cookies.js'
],
                        dest: theme_path + '/js/main.js'
                    }
                ]
            }
},
uglify: {
            dist: {
                files: [{
                    src: theme_path + '/js/main.js',
                    dest: theme_path + '/js/main.min.js'
                }]
            }
        }
});
