### ISSUE TITLE
Bootstrap navigation

### ISSUE THREAD

**Issue by SitoD** [webcomm/magento-boilerplate#103]
Hi! , what a great work you did, thank you!  but since you are the builder of this good template, can I ask you a question?

I need to display a logo-image in the middle of the navigation bar, between two links ....normally in bootstrap I make 5 list items, with the 3e one the image...
Can I realize this in this theme?  and how to do this please?

Regards!
Sito

**Comment by bencorlett** [comment]
You sure can do this in the boilerplate. You can do anything that you'd like with regards to Magento, HTML and CSS development.

I offer consulting work at an hourly rate. Drop an email to hello [at symbol] webcomm.io and we can talk!
