### ISSUE TITLE
/development -> unbound variables generate gulp error

### ISSUE THREAD

**Issue by ottonet** [webcomm/magento-boilerplate#106]
boilerplate/development generates following error running gulp:

[14:50:59] gulp-notify: [Error running Gulp] bower_components/magento-boilerplate/assets/stylesheets/magento-boilerplate:57: unbound variable $include-grid-component

Apparently this whole thing is not working, as commenting out above line just generates an error on the next line: 
> // We only include the components out of Foundation that are required. These variables appear to never be defined,
> // however they're dynamically generated by the Boilerplate's Gulpfile. This allows these components, in
> // conjunction with their JavaScript counterparts, to be included, conditionally, per site. Rock on!

New to foundation and sass so no idea (yet) what's going on here...

**Comment by ottonet** [comment]
Changing config.json: 

          "package": "boilerplate",

to

          "package": "myown-package-name",

Fixed the issue. However I did expect to be able to use 'boilerplate' as a (default) package name to generate a default/demo

**Comment by ottonet** [comment]
Of course changing config.json helps; there is no scss to compile in the new package - so it compiles just fine. Back to square one :(

**Comment by bencorlett** [comment]
There is no support for dev as yet. Checkout the Magento-boilerplate-demo repo, that contains the things you would require.  :)

Sent from my iPhone

Please excuse my brevity
