### ISSUE TITLE
BrowserSync instead of LiveReload and Bless?

### ISSUE THREAD

**Issue by royduin** [webcomm/magento-boilerplate#107]
BrowserSync does have some more features than LiveReload and doesn't require browser plugins. An idea to switch LiveReload for BrowserSync?

And is it an idea to add Bless? An reference to it was in the gulpfile in an earlier version but is removed. I've spend a couple of days figuring out what the problem was in IE, Bless was the solution!

**Comment by bencorlett** [comment]
Hi there,

The upcoming version `3.0` of this theme has switched to BrowserSync. I'm not planning on adding on adding this to version `2.0` at this time as it's a fairly big development change.

Keep your eye out for the `3.0` announcement. Lots of goodies, such as installing the assets with `bower` and using a single `gulpfile.js` in the root directory that supports multiple themes, and no more dropping copies of the boilerplate in each theme you create. Much tidier. Bliss.

**Comment by royduin** [comment]
Nice! I'm looking forward to version 3.0!
