### ISSUE TITLE
Adding uncss to gulp file?

### ISSUE THREAD

**Issue by ryan-who** [webcomm/magento-boilerplate#113]
Hi,

I was hoping to use [gulp-uncss](https://www.npmjs.com/package/gulp-uncss) to remove unused css selectors and reduce the size of the css file for my magento store, but I'm new to gulp and need some help. I've installed gulp-uncss via npm and have added ``` var uncss = require('gulp-uncss'); ``` to the gulp file. I placed the example code from npmjs.com into gulpfile.js and tried to fit it to the boilerplate, but gulp doesn't run uncss.

I'd appreciate any help in getting uncss running with the boilerplate, thanks.

```
gulp.task('default', function() {
    return gulp.src('src/less/*.less')
        .pipe(less())
        .pipe(concat('style.css'))
        .pipe(uncss({
            html: ['index.html', 'http://example.com']
        }))
        .pipe(gulp.dest('./out'));
});
```

**Comment by bencorlett** [comment]
I'm not familiar with this module actually. It looks cool!

It appears that, maybe, you need to either give it an array of files that exist on your filesystem. Obviously, Magento's URLs don't respond to single files, so this becomes quite tricky. 

```js
gulp.task('default', function() {
    return gulp.src('src/less/*.less')
        .pipe(less())
        .pipe(concat('style.css'))
        .pipe(uncss({
            html: ['../../../../app/design/frontend/boilerplate/default/template/**/*.phtml']
        }))
        .pipe(gulp.dest('./out'));
});
```

My guess is you need to do something like the example above. Pass through the relative path to your PHTML files which contain the CSS selectors.

I'm going to look into this more in the future, particularly for the upcoming version `3.0` of this project. Unless contributed by a community member, I won't implement this in version `2.0` at this stage.

Cool suggestion, love it!
