### ISSUE TITLE
Magento 1.9.1.0 compatibility 

### ISSUE THREAD

**Issue by BassemN** [webcomm/magento-boilerplate#115]
Hi,

Is this theme compatible with Magento 1.9.1.0?

Thanks,

**Comment by bencorlett** [comment]
AFAIK it is. Check other issues I remember a discussion about it. 

Sent from my iPhone

Please excuse my brevity

**Comment by emedchill** [comment]
There is an issue with configurable swatches and by proxy the image swap.

**Comment by rubytastic** [comment]
Ok im now using this for new project.
I could fix if anyone could share some details on what exactly is broken and how we could fix it.

Perhaps combine efforts? 
Glad to give back to this project.

**Comment by bencorlett** [comment]
Dup of #102.
