### ISSUE TITLE
Trouble with Safari Mac

### ISSUE THREAD

**Issue by mhanzkj** [webcomm/magento-boilerplate#117]
Theme got broken on Safari Mac, How do I fix this?

**Comment by bencorlett** [comment]
It was developed on Safari on a Mac (I’m not a Chrome user unless for cross-browser testing).

Can you elaborate?

**Comment by mhanzkj** [comment]
Everything on the page is broken. Click my site out. humanhairextensionsonline.com.
It works on firefox and chrome but not on safari.

**Comment by bencorlett** [comment]
Have you checked out the original boilerplate on your Mac? It appears fine for me. I develop client sites daily using it too. That suggests the error is maybe on your end. 

Sent from my iPhone

Please excuse my brevity
