### ISSUE TITLE
Unminimized script.js

### ISSUE THREAD

**Issue by mgarciadelojo** [webcomm/magento-boilerplate#123]
First of all, thank you for this project. It's very useful for me to start coding my own theme using bootstrap.

In second place, is there any way to upload to the repository an unminimized version of the `script.js` file? I've coded an special menu with bootstrap, and I need to disable only this functionality.

Thank you :)

**Comment by octobresept** [comment]
Are you looking for magento-boilerplate/skin/frontend/boilerplate/default/src/js/script.js ?

**Comment by mgarciadelojo** [comment]
Yes, I wonder if you have it unminified, because I want to disable some functionality.

**Comment by octobresept** [comment]
Actually, magento-boilerplate/skin/frontend/boilerplate/default/src/js/script.js isn't minified

**Comment by mgarciadelojo** [comment]
Are you sure? I see it minified:
https://github.com/webcomm/magento-boilerplate/blob/master/skin/frontend/boilerplate/default/js/script.js

**Comment by mgarciadelojo** [comment]
Sorry, my bad. I didn't see the src directory :(

**Comment by jwittorf** [comment]
This can be closed, too? Sorry for getting on your nerves about this but I think it could help others in my situation, too. Gonna check the other issues and then I'm looking forward to using the theme, looks very promissing so far, thanks for the efforts!
