### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by rossmc** [webcomm/magento-boilerplate#124]
Hi I'm developing my own theme with TB and Compass SASS and I was wondering how you got around the issue of Bootstrap 3's dropdown menu disappearing on click due to a conflict with prototype.js?

I found this solution on StackExchange but was wondering if you had a better solution?
http://stackoverflow.com/a/28214747/1814446

I hope you don't mind me contacting you this way and understand if you don't have time to answer.

Thanks,
Ross

**Comment by octobresept** [comment]
Not sure but I think you should look at https://github.com/webcomm/magento-boilerplate/blob/master/skin/frontend/boilerplate/default/src/js/script.js, there's a function about prototype/bootstrap compatibility

**Comment by rossmc** [comment]
Thanks, that's really helpful.

By the way I found a good plugin which you can use to make your Bootstrap nav menu multi level and open on hover rather than click on desktops.
https://github.com/vadikom/smartmenus
http://vadikom.github.io/smartmenus/src/demo/bootstrap-navbar.html

**Comment by octobresept** [comment]
Some people may find this useful but I guess the next version of Magento Boilerplate will use Foundation

**Comment by rossmc** [comment]
Interesting, why have you chosen Foundation over BS.  There does not seem to be a huge amount separating them.

Best of luck

**Comment by octobresept** [comment]
You'll have to wait Ben Corlett's explanations

**Comment by rossmc** [comment]
no problem :)
