### ISSUE TITLE
Either my error or Composer issue

### ISSUE THREAD

**Issue by anthonybachour** [webcomm/magento-boilerplate#127]
Hey I tried using the composer method to get the theme but when I tried to copy it over I discovered that the app folder doesn't exist (vendor/webcom.../app) in magento-boilerplate there's only assets and src folders.

Sorry if this is a dumb mistake on my part but I've never used composer before!

**Comment by bencorlett** [comment]
Hi there,

I believe this may be caused because I’m in the process of rolling out V3 of this project.

I’ve updated the README accordingly.

You just need to change your composer.json file, so that instead of requiring “dev-master”, you require "2.0.x-dev”.

Let me know how you go!

**Comment by anthonybachour** [comment]
Hey! That worked, you won't believe all the things I tried to make it work with composer haha. Thanks!

**Comment by bencorlett** [comment]
Haha. It can be quite daunting when you first begin.

Glad to hear you’re sorted.

**Comment by jwittorf** [comment]
So this can be closed? I'm about to install the module but before I like to check all the issues to prevent some bad suprises. I'd be more confident about installing a module with very few issues ;)
