### ISSUE TITLE
sass / bourbon.io

### ISSUE THREAD

**Issue by theskillwithin** [webcomm/magento-boilerplate#130]
Hello just wondering if you knew how to get magento to stop using compass and use the bourbon.io (libsass) instead.  with sass.

**Comment by bencorlett** [comment]
This sounds like something to do with your specific setup. I don’t have compass on any of my servers and run it fine. Maybe check your bash $PATH to see if maybe gulp-sass defaults to systemwide installations first.

**Comment by bencorlett** [comment]
Let me know how you go :)

**Comment by theskillwithin** [comment]
Wait you have rwd theme without compass?!  This is what I have been looking
for!  Where do I find this

**Comment by bencorlett** [comment]
The new upcoming version of this theme (v3) is actually built on SASS and uses libsass :)

Primative docs are at https://github.com/webcomm/magento-boilerplate-app <https://github.com/webcomm/magento-boilerplate-app> but I haven’t released it yet so any bugs or issues you have, are to be expected.

I’m using it on around 5 or 6 client sites before I release it to the public :)

**Comment by theskillwithin** [comment]
This is fantastic news!

I don't see the sass files, I see @import "magento-boilerplate";

I have never used gulp before so this might be my biggest hurtle. (Currenly
I use codekit to compile I wonder how this will work with gulp thrown in
the mix, I also have proprose)

I have never used foundation either, but I think since Magento sites are
usually bigger projects its going to be for the best.

Composer installs the actual magento files? very interesting.   Is this
more beneficial than just having the files already?

So excited going to try this out now!

Thank you!!!
Austin

**Comment by bencorlett** [comment]
Correct. So the new version utilises 3 package managers:

Composer is used to install PHP dependencies (php modules etc)
Bower is used to install asset dependencies (find Foundation / jQuery etc)
Gulp (a NodeJS tool) is used as a task runner (what CodeKit does).

There’s a learning curve and I plan on building a lot of seriously good documentation for it as soon as I feel it’s ready and we can go live with it :)
