### ISSUE TITLE
Subcategories TopMenu Disabled?

### ISSUE THREAD

**Issue by tiarly** [webcomm/magento-boilerplate#14]
Did you guys disable subcategories in the topMenu or is it a real bug to be fixed?

When i try to create a subcategory in the admin it is being rendered by magento, but it never shows either on hover or click events.

**Comment by failasuf** [comment]
How to add mega menu in Theme Boilerplate use code,?

**Comment by bencorlett** [comment]
@failasuf I would look at adding your own `local.xml` under `app/design/frontend/:package/:theme/layout.local.xml` and make your XML layout modifications there.

You may need to disable or remove `app/etc/modules/Webcomm_MagentoBoilerplate.xml`.

Hope this helps.

**Comment by failasuf** [comment]
@bencorlett  can i edit this? to become Mega Menu?
app\code\community\Webcomm\BootstrapNavigation\Block\Page\Html\Topmenu.phtml

But i dont know to edit, become Mega Menu

thanks.

**Comment by kimbo6365** [comment]
I've created a custom module to manually override the maxdepth set in the boilerplate module, paired with some CSS to show the nested menu.

Here are some instructions on how to do it:

1. Create a custom module in `app/code/local`--I'm using the namespace `KimBryant` and calling my module `BootstrapNavigationOverride`, so my file structure looks like: `app/code/local/KimBryant/BootstrapNavigationOverride`

2. Create a new file called `Maxdepth.php` at `app/code/local/KimBryant/BootstrapNavigationOverride/Model/System/Config/Source` and use the below code as the contents. I'm just using 3 nested categories, but theoretically you could add as many as you need.

        <?php
        class KimBryant_BootstrapNavigationOverride_Model_System_Config_Source_Maxdepth extends Webcomm_BootstrapNavigation_Model_System_Config_Source_Maxdepth {
            /**
             * Options getter
             *
             * @return array
             */
            public function toOptionArray()
            {
                return array(
                    array('value' => 3, 'label'=>Mage::helper('adminhtml')->__('3')),
                    array('value' => 2, 'label'=>Mage::helper('adminhtml')->__('2')),
                    array('value' => 1, 'label'=>Mage::helper('adminhtml')->__('1')),
                );
            }

            /**
             * Get options in "key-value" format
             *
             * @return array
             */
            public function toArray()
            {
                return array(
                    3 => Mage::helper('adminhtml')->__('3'),
                    2 => Mage::helper('adminhtml')->__('2'),
                    1 => Mage::helper('adminhtml')->__('1'),
                );
            }
        }

3. Now you'll need to create the config files for the custom module. Create a file called `config.xml` at `app/code/local/KimBryant/BootstrapNavigationOverride/etc/` and use the below code as the contents:

        <?xml version="1.0"?>

        <config>
            <modules>
                <KimBryant_BootstrapNavigationOverride>
                    <version>0.1.0</version>
                </KimBryant_BootstrapNavigationOverride>
            </modules>
            <global>
                <models>
                    <kimbryant_bootstrapnavigationoverride>
                        <class>KimBryant_BootstrapNavigationOverride_Model</class>
                    </kimbryant_bootstrapnavigationoverride>
                    <webcomm_bootstrapnavigation>
                        <rewrite>
                            <maxdepth>KimBryant_BootstrapNavigationOverride_Model_System_Config_Source_Maxdepth</maxdepth>
                        </rewrite>
                    </webcomm_bootstrapnavigation>
                </models>
            </global>
            <default>
                <catalog>
                    <navigation>
                        <max_depth>3</max_depth>
                        <top_in_dropdown>1</top_in_dropdown>
                        <top_in_dropdown_prefix>View All</top_in_dropdown_prefix>
                        <top_in_dropdown_suffix></top_in_dropdown_suffix>
                    </navigation>
                </catalog>
            </default>
        </config>

4. Now create a file called `system.xml` in the same directory with the below code as content:

        <?xml version="1.0"?>

        <config>
            <sections>
                <catalog>
                    <groups>
                        <navigation>
                            <fields>
                                <max_depth>
                                    <label>Top-Level Navigation Category Depth</label>
                                    <frontend_type>select</frontend_type>
                                    <source_model>kimbryant_bootstrapnavigationoverride/system_config_source_maxdepth</source_model>
                                    <comment>How many levels of nested categories to display</comment>
                                </max_depth>
                            </fields>
                        </navigation>
                    </groups>
                </catalog>
            </sections>
        </config>



5. Finally, you'll need to activate your module. Create a file called `KimBryant_BootstrapNavigationOverride.xml` in `app/etc/modules` with the below content:

        <?xml version="1.0"?>

        <config>
            <modules>
                <KimBryant_BootstrapNavigationOverride>
                    <active>true</active>
                    <codePool>local</codePool>
                    <depends>
                        <Webcomm_BootstrapNavigation/>
                    </depends>
                </KimBryant_BootstrapNavigationOverride>
            </modules>
        </config>



Now you should be able to go into your settings at System > Configuration > Catalog > Category Top Navigation and change the setting in the "Top-Level Navigation Category Depth" dropdown and style away!

**Comment by bencorlett** [comment]
^^ awesome :)

**Comment by Tomasz-Silpion** [comment]
Some css like

```
.nav .dropdown-menu .parent:hover {
    position: relative;
}

.nav .dropdown-menu .parent:hover > ul {
    display: block;
    left: 100%;
}
```

Solves the issue.
