### ISSUE TITLE
jquery library?

### ISSUE THREAD

**Issue by derrtas** [webcomm/magento-boilerplate#140]
Hi

This is first time i use magento-boilerplate i have added a simple jquery function which adds classes to couple html tags on my website however when i put link to jquery library in header then dropdown top menu isn't working -> on click it takes me to the parent category instead of dropping down and showing subcategories.

**Comment by bencorlett** [comment]
Was it working prior?

Can you add:

```js
jQuery(document).ready(function($) {
});
```

jQuery must be working in `$.noConflict()` mode because Prototype is using the `$` global variable.
