### ISSUE TITLE
Bootstrap thumbnails missing

### ISSUE THREAD

**Issue by vincentwinkel** [webcomm/magento-boilerplate#142]
Thanks for your very powerful boilerplate !
I wanted to use Bootstrap thumbnails but there are not included in the global less file.
You need to add file skin/frontend/.../src/less/thumbnails.less which contains : 
```less
@import "@{bootstrap-path}/thumbnails.less";
```
And to include this file in skin/frontend/.../src/less/style.less as following : 
```less
@import "thumbnails.less";
```
Finally, relaunch gulp and enjoy.

Maybe other Bootstrap components are missing but I didn't check.
Vincent

**Comment by bencorlett** [comment]
Hi Vincent,

Thank you for this nice little tutorial, I hope it helps others outs in this process.

By design, I only included components which are required, everything else is opt-in, exactly as you have done :)
