### ISSUE TITLE
White Page

### ISSUE THREAD

**Issue by BornLuna** [webcomm/magento-boilerplate#144]
I've tried to install this 6 times so far. I've literally tried everyting. I've installed it on a ubuntu 14.04 x64 server using apache, and nginx, and windows 10 x64 using xampp..

Everytime I follow the install instructions, and the website is a white screen... What is happening.. 

I'm using magento 1.9.2.3

**Comment by bencorlett** [comment]
Just the home page?

Did you turn symlinks on?

Sent from my iPhone

Please excuse my brevity

**Comment by BornLuna** [comment]
@bencorlett uhh.. Well on windows I did 

`mklink /J vendor/webcomm/magento-boilerplate/app/design/frontend/boilerplate app/design/frontend/harvest`

is this not correct?

**Comment by BornLuna** [comment]
Here's what I did on windows...

I created `composer.json` and copied everything from the readme into that file
Then ran `composer install`
Then ran `cp vendor/webcomm/magento-boilerplate/index.php .`
and `cp -Rf vendor/webcomm/magento-boilerplate/app/design/frontend/boilerplate app/design/frontend/harvest`
and `cp -Rf vendor/webcomm/magento-boilerplate/skin/frontend/boilerplate skin/frontend/harvest`

Then went into the admin, and change the package to `harvest`

[Here is the image of my admin config](http://i.imgur.com/R9olmyE.jpg)

and when I press save and go to the website, it's a white page

**Comment by bencorlett** [comment]
In the admin, under system > configuration > advanced > developer you have to instruct Magento to use them. 

Sent from my iPhone

Please excuse my brevity

**Comment by BornLuna** [comment]
@bencorlett I went into the advance developer settings and turned on `Allow Symlinks`, and I still get a white screen :cry:

**Comment by bencorlett** [comment]
Just the home page?

I've never worked with anybody developing on Windows so anything specific to that I'm not sure of. Check error logs, var/report/ etc. make sure logging is turned on within Magento. 

Sent from my iPhone

Please excuse my brevity

**Comment by BornLuna** [comment]
@bencorlett well... It randomly started working.. After 4 hours of trying to figure this out it randomly started working.. 

Windows is the worst.. Sorry about this

**Comment by Webmasterei** [comment]
Have you used the rights management and checked all block types appearing on the homepage to be in it?
See here: https://magentary.com/kb/cms-pages-transactional-emails-broken-after-supee-6788-patch/

**Comment by bencorlett** [comment]
No I've not made a script to whitelist blocks. This version of the boilerplate has been on the back burner because of Webcomm/Magento-boilerplate-app :)

Sent from my iPhone

Please excuse my brevity
