### ISSUE TITLE
Pagination of catalog search broken

### ISSUE THREAD

**Issue by z-v** [webcomm/magento-boilerplate#145]
On my several sites running boilerplate, they all have a strange issue on the search page.

1. Start a search (assuming you'll retrieve multiple pages of search results)
2. Select page 2, 3, or 4
3. Try to go to another page of the search (with arrows or numbers)

Then unable to move from the page you originally selected

This is on my sites running 1.9.2

**Comment by bencorlett** [comment]
Hmm that’s peculiar. Would you have a sample where this happens?

**Comment by z-v** [comment]
http://bit.ly/20UTysz

**Comment by bencorlett** [comment]
Strange.

I noticed that

```
http://www.ifancyone.com/catalogsearch/result/index/q/tootin/p/4/?p=3&q=tootin
```

Is your URL. Unless Magento 1.9.2 changed something (which I'm very unaware of), you'd typically see

```
http://www.ifancyone.com/catalogsearch/result/index?p=3&q=tootin
```

The extra junk looks like it's being added by an SEO extension. Nothing we do should have any effect on the URL generated internally by Magento for pagination...

Going to close this now and suggest you disable any other third party extensions that hijack that URL. It's possible they override the Magento pagination as well and as a result there's a conflict introduced.

Feel free to open if you can narrow it down to something specific to the boilerplate :)
