### ISSUE TITLE
Magento 2 version?

### ISSUE THREAD

**Issue by craigcarnell** [webcomm/magento-boilerplate#148]
What are the changes of you releasing a Magento 2 version? Thank you

**Comment by Webmasterei** [comment]
AFAIK it's rather "write new" then "change"

**Comment by septoctobre** [comment]
Changes ? Chances ?

**Comment by bencorlett** [comment]
What @Webmasterei said. I don't actually know if/when I'll be pursuing this, at this stage. M2 has a (sub-optimal, but acceptable) asset pipeline structure and I don't see a need to rival this, at this stage.
