### ISSUE TITLE
How to add Bootstrap Tabs in Boilerplate?

### ISSUE THREAD

**Issue by webdaDev** [webcomm/magento-boilerplate#156]
Hi,

i think the prototype Framework is the Problem because my Bootstrap tabs didnt "work" like they should.

It does not switch on click. I am sure you got a solution for this (you also did this for the navigation with Bootstrap) but i dont find any on my search.

Can you please help?

regards Johannes

**Comment by bencorlett** [comment]
Hey, [this](https://github.com/webcomm/magento-boilerplate/blob/2.0/skin/frontend/boilerplate/default/src/js/script.js#L53-L69) should get you started.

I haven't had a requirement for this as yet and since I'm moving away from Bootstrap in [V3](https://github.com/webcomm/magento-boilerplate-app) it would be a feature that I'd be happy to accept from a community member in a PR, but it would be very much down the bottom of my priority list and I couldn't give a date that I'd have the time to implement this.

I hope this helps :)

**Comment by webdaDev** [comment]
Adding the "'bower_components/bootstrap/js/tab.js'," tab.js to the gulpfile.js AND
adding the tab class to the script.js solved my Problem with Bootstrap Nav Pills and Tabs.

           $('*').on('show.bs.dropdown show.bs. hide.bs.tab hidden.bs.tab', function(e) {
                $(e.target).addClass('bs-prototype-override');
            });

            $('*').on('hidden.bs.collapse', function(e) {
                $(e.target).removeClass('bs-prototype-override');
            });

**Comment by frameworkerrs** [comment]
i have added this bower_components/bootstrap/js/tab.js to gulpfile.js .. but still i cant get tabs section in product details page {http://magentoboilerplate.webcomm.com.au/furniture/living-room/ottoman.html}

Details, Additional Information etc come one by one.. not as tabs..

can anybody help me?

**Comment by bencorlett** [comment]
Hi, I can't remember if the HTML markup of the product page is setup for tabs or not. Can you confirm this? If not, there is work required for you to modify magento's XML layouts / PHTML templates. 

If there is already suitable markup, check for JavaScript errors. 

Sent from my iPhone

Please excuse my brevity

**Comment by frameworkerrs** [comment]
thanks for your reply..

this is my tab code.. seems bower_components tab.js is not working

<div class="product-collateral toggle-content tabs">
<dl id="collateral-tabs" class="collateral-tabs">
<dt class="tab"><span>description</span></dt>
<dd class="tab-container">
<div class="tab-content">    <h2>Details</h2>
    <div class="std">
        Are you planning to present your child his first mobile handset
that is not too expensive and is also easy to operate? Then get this Nokia
105 feature phone that has a single SIM.

Screen Type and Size

This cyan-coloured handset has a 3.55cm LCD screen with a QVGA resolution.
You can easily browse through your contacts and read messages without
hurting your eyes.

Battery

The phone is powered by a Li-ion battery with a capacity of 800mAh that
gives 12 hours talk time and 842 hours standby time.

Storage

This phone has 8 MB internal memory and features SMS, phone book and call
memory as well.

Additional Features

The handset also features a digital clock, calculator, flashlight, games,
alarm, pin code security and a splash-proof keypad.    </div>
</div>
</dd>
<dt class="tab"><span>Incrediants</span></dt>
<dd class="tab-container">
<div class="tab-content"></div>
</dd>
</dl>
</div>
