### ISSUE TITLE
JS at bottom of page?

### ISSUE THREAD

**Issue by npearson72** [webcomm/magento-boilerplate#157]
Why is the JS at the top of the page? This isn't really best practice and Google penalizes you for it. Check out Google's PageSpeed tool.

Is it possible to move the JS to the bottom?

**Comment by bencorlett** [comment]
If you checkout [webcomm/magento-boilerplate-app](https://github.com/webcomm/magento-boilerplate-app), we're including a [PageSpeed module](https://github.com/webcomm/magento-boilerplate-app/blob/master/composer.json#L33) to achieve this moving forward.

Feel free to implement this in your projects or shoot a PR for v2 :)
