### ISSUE TITLE
No caret icon or category link in dropdown

### ISSUE THREAD

**Issue by MikeOntry** [webcomm/magento-boilerplate#47]
Just want to start off by saying this is an awesome project. Thanks for making it free and easy!

I just installed this onto magento 1.8.1.0 from the .zip file. I turned the theme on and everything seems to be working great except my dropdowns do not have the caret icon and there is not a category link in the dropdown like on the demo site. Any ideas on what's going wrong?

**Comment by bencorlett** [comment]
To be honest, I'm not following. You can **disable module output**, and **disable modules**. Disabling output only renders the `toHtml()` method of a block to return nothing. Class overrides, etc still have effect. Disabling a module by editing `app/etc/modules/*.xml` is the same as effectively deleting all of it's files off your server.
