### ISSUE TITLE
what is this for? ->.bs-prototype-override utilities.js

### ISSUE THREAD

**Issue by matthewdolman** [webcomm/magento-boilerplate#52]
In utilities.less we have

.bs-prototype-override{
    display: block !important;
}

I am finding it being applied to a dropdown in a input group I am creating but the original element was display:table-cell and so this is breaking the input group.

Am I safe just to change this to display:table-cell or will it break something else I can't see?

**Comment by webdaDev** [comment]
This Snippet is for Bootstrap Dropdown only. or?

Is there a solution for "nav nav-tabs"?
I put a "nav nav-tabs" on my "homepage" and it didn´t work.

All of the following did not work:

http://www.w3schools.com/bootstrap/bootstrap_tabs_pills.asp

**Comment by webdaDev** [comment]
Adding the "'bower_components/bootstrap/js/tab.js'," tab.js to the gulpfile.js AND
adding the tab class to the script.js solved my Problem with Bootstrap Nav Pills and Tabs.

`$('*').on('show.bs.dropdown show.bs. hide.bs.tab hidden.bs.tab', function(e) {
                $(e.target).addClass('bs-prototype-override');
            });

            $('*').on('hidden.bs.collapse', function(e) {
                $(e.target).removeClass('bs-prototype-override');
            });`
