### ISSUE TITLE
Question: Will this work with Magento Enterprise Edition? - Not An Issue

### ISSUE THREAD

**Issue by imaginethepoet** [webcomm/magento-boilerplate#63]
You may not have an answer to this just wondering if there is really that much difference between community and enterprise.

Thank you,

**Comment by jasontipton** [comment]
Just as a note to using this theme for enterprise if you want to re-add the My Cart dropdown in the header, I have been told this article was useful in integrating that into the theme.
http://dltr.org/blog/magento/118/Magento-add-sidebar-mini-cart-on-the-header
