### ISSUE TITLE
IE8 support and respond.js broken with latest set of updates

### ISSUE THREAD

**Issue by gfxpixeldesigns** [webcomm/magento-boilerplate#65]
Since applying the recent set of updates i have noticed IE8 is no longer working- the media queries are not getting applied so something must have upset the respond.js integration.

**Comment by bencorlett** [comment]
I think I'll leave this one out for now. Personally, not overly interested in IE8 support. If you find a fix, please submit it back as a PR :)

The upcoming version `3.0` of this theme supports IE9+ :)
