### ISSUE TITLE
Carousel CSS not loading in IE9

### ISSUE THREAD

**Issue by gfxpixeldesigns** [webcomm/magento-boilerplate#81]
I've just noticed this issue in IE9 and below. On a default install if i add a carousel slideshow to the homepage and load up IE9, only one line of the carousel CSS is being loaded. It works perfectly fine in IE10+ and other browsers. I've tried older jquery versions but no luck although jquery 2.x should be fine in IE9. The carousel is just showing stacked images as a result of having no css. I'm not sure what the problem could be, i mean how can the css be loaded fine in IE10 but not IE9? Its a bit of a mystery to me this one but perhaps you guys know whats going on?

**Comment by bencorlett** [comment]
Looks to be something in relation to #85.
