### ISSUE TITLE
Navigation not possible to disable per store view

### ISSUE THREAD

**Issue by joekersh** [webcomm/magento-boilerplate#89]
I have a Magento installation running several shops, i have the Webcomm theme installed on one of them but the others are running older themes until i can update. How do i turn the navigation off for the other shops, so that its just on the one website.

Thanks

**Comment by SAN1TAR1UM** [comment]
I would suggest maybe using Mage::app()->getWebsite()->getCode() instead of ID. I have a few different dev, stage, and working magento instances and the IDs aren't always the same between them, but the code can be since it's set in the Admin Panel.

Either way awesome solution, thanks for sharing.

**Comment by bencorlett** [comment]
Sick :)
