### ISSUE TITLE
script.js breaks zopim livechat v1

### ISSUE THREAD

**Issue by viiter** [webcomm/magento-boilerplate#90]
when using the boilerplate with zopim livechat module once the zopim chat window is open you are unable to minimize it, these 4 lines are causing the issue, once commented out the issue is resolved but i am not sure if it breaks anything else

```
e("*").on("show.bs.dropdown show.bs.collapse", function(t) {
	e(t.target).addClass("bs-prototype-override")
}), e("*").on("hidden.bs.collapse", function(t) {
	e(t.target).removeClass("bs-prototype-override")
})
```

**Comment by bencorlett** [comment]
Yeah, they're used to add CSS that makes dropdowns play nice with both Bootstrap and Magento's JavaScript libraries. Check the CSS for what the `.bs-prototype-override` class does.
