### ISSUE TITLE
Asset Dependency Management and Automatic Compilation

### ISSUE THREAD

**Issue by alex4allofyou** [webcomm/magento-boilerplate#92]
"The first thing to do this is install Bower and gulp.js (both are NodeJS applications)."

I have not used these applications before, maybe a silly question, but I don't get how to get this working on the server of my host. How does this work? Install on Windows, compile and than move the compiled style.css and jscript.js files?

I only have access with the server with Shell, but there is no possibility to install these on the server. 
So how does it auto-compile?

**Comment by bencorlett** [comment]
Heya,

There's tuts out there on all these tools.

If you can't install the software, I would encourage you to compile locally, then commit the compiled code into your repo, or if you're not using version control (shame), FTP the compiled code up.

**Comment by alex4allofyou** [comment]
Yeah, in the meantime I watched also his clips, used gulp and experimented. The workflow is badly documented but I wanted to learn it so persevered and finally it clicked. I am now using Sublime Text SFTP and edit locally and upload the files to server. I am glad I took the time and effort to learn it, it was worth it, Thanks for your comment.
