### ISSUE TITLE
Review css generated code

### ISSUE THREAD

**Issue by microcipcip** [webcomm/magento-boilerplate#94]
I suggest a review of the css code that is being generated, as there is a considerable repetition of selectors. Apart from the performance issues, this is blocking css rendering on IE8/IE9 due to the 4000 selectors bug.

I have noticed for example that on [cart.less](https://github.com/webcomm/magento-boilerplate/blob/master/skin/frontend/boilerplate/default/src/less/cart.less#L194),  for .cart .totals you are extending the whole .table bootstrap class, this will generate a huge list of selectors. I have replaced that with a simple table {width: 100%;} and it didn't change anything in terms of styling. 

The same problem is on [tables.less](https://github.com/webcomm/magento-boilerplate/blob/master/skin/frontend/boilerplate/default/src/less/tables.less#L26-L27) and in the forms. Each removal decrease the css file of 10k or more.

**Comment by bencorlett** [comment]
This has been fixed somewhat in version `2.0` and overhauled in version `3.0`.
