### ISSUE TITLE
Reloading the modal / lightbox script?

### ISSUE THREAD

**Issue by onyx86** [webcomm/magento-boilerplate#95]
We are using a plugin to update the product image block based on the users color swatch selection (ie show only red widget images if red swatch is clicked). The plugin reloads the media.phtml content after clicking a swatch and replaces the old image block with the new one. 

The trouble im having is that the modal / lightbox no longer pops up after you change the color. I believe we need to reload the bootstrap modal js after reloading the media.phtml content. The color swatch plugin has an "onComplete" section to run code after it does its thing. What code should I run to restore the lightbox functionality?

**Comment by bencorlett** [comment]
Yeah this is related to #102. Is on the list of things to fix for the latest version of Magento.
